update=23/12/2018 11:24:23 AM
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=../../kicad/Libraries
[eeschema/libraries]
LibName1=1Wire-AC_Zoning-rescue
LibName2=power
LibName3=device
LibName4=transistors
LibName5=conn
LibName6=linear
LibName7=regul
LibName8=74xx
LibName9=cmos4000
LibName10=adc-dac
LibName11=memory
LibName12=xilinx
LibName13=microcontrollers
LibName14=dsp
LibName15=microchip
LibName16=analog_switches
LibName17=motorola
LibName18=texas
LibName19=intel
LibName20=audio
LibName21=interface
LibName22=digital-audio
LibName23=philips
LibName24=display
LibName25=cypress
LibName26=siliconi
LibName27=opto
LibName28=atmel
LibName29=contrib
LibName30=valves
LibName31=A:/kicad/Kicad Offical Libraries/kicad-library/library/74xgxx
LibName32=A:/kicad/Kicad Offical Libraries/kicad-library/library/74xx
LibName33=A:/kicad/Kicad Offical Libraries/kicad-library/library/ac-dc
LibName34=A:/kicad/Kicad Offical Libraries/kicad-library/library/actel
LibName35=A:/kicad/Kicad Offical Libraries/kicad-library/library/adc-dac
LibName36=A:/kicad/Kicad Offical Libraries/kicad-library/library/Altera
LibName37=A:/kicad/Kicad Offical Libraries/kicad-library/library/analog_devices
LibName38=A:/kicad/Kicad Offical Libraries/kicad-library/library/analog_switches
LibName39=A:/kicad/Kicad Offical Libraries/kicad-library/library/atmel
LibName40=A:/kicad/Kicad Offical Libraries/kicad-library/library/audio
LibName41=A:/kicad/Kicad Offical Libraries/kicad-library/library/battery_management
LibName42=A:/kicad/Kicad Offical Libraries/kicad-library/library/bbd
LibName43=A:/kicad/Kicad Offical Libraries/kicad-library/library/brooktre
LibName44=A:/kicad/Kicad Offical Libraries/kicad-library/library/cmos_ieee
LibName45=A:/kicad/Kicad Offical Libraries/kicad-library/library/cmos4000
LibName46=A:/kicad/Kicad Offical Libraries/kicad-library/library/conn
LibName47=A:/kicad/Kicad Offical Libraries/kicad-library/library/contrib
LibName48=A:/kicad/Kicad Offical Libraries/kicad-library/library/cypress
LibName49=A:/kicad/Kicad Offical Libraries/kicad-library/library/dc-dc
LibName50=A:/kicad/Kicad Offical Libraries/kicad-library/library/device
LibName51=A:/kicad/Kicad Offical Libraries/kicad-library/library/digital-audio
LibName52=A:/kicad/Kicad Offical Libraries/kicad-library/library/diode
LibName53=A:/kicad/Kicad Offical Libraries/kicad-library/library/display
LibName54=A:/kicad/Kicad Offical Libraries/kicad-library/library/dsp
LibName55=A:/kicad/Kicad Offical Libraries/kicad-library/library/elec-unifil
LibName56=A:/kicad/Kicad Offical Libraries/kicad-library/library/ESD_Protection
LibName57=A:/kicad/Kicad Offical Libraries/kicad-library/library/ftdi
LibName58=A:/kicad/Kicad Offical Libraries/kicad-library/library/gennum
LibName59=A:/kicad/Kicad Offical Libraries/kicad-library/library/graphic
LibName60=A:/kicad/Kicad Offical Libraries/kicad-library/library/hc11
LibName61=A:/kicad/Kicad Offical Libraries/kicad-library/library/intel
LibName62=A:/kicad/Kicad Offical Libraries/kicad-library/library/interface
LibName63=A:/kicad/Kicad Offical Libraries/kicad-library/library/ir
LibName64=A:/kicad/Kicad Offical Libraries/kicad-library/library/Lattice
LibName65=A:/kicad/Kicad Offical Libraries/kicad-library/library/linear
LibName66=A:/kicad/Kicad Offical Libraries/kicad-library/library/logo
LibName67=A:/kicad/Kicad Offical Libraries/kicad-library/library/maxim
LibName68=A:/kicad/Kicad Offical Libraries/kicad-library/library/memory
LibName69=A:/kicad/Kicad Offical Libraries/kicad-library/library/microchip
LibName70=A:/kicad/Kicad Offical Libraries/kicad-library/library/microchip_dspic33dsc
LibName71=A:/kicad/Kicad Offical Libraries/kicad-library/library/microchip_pic10mcu
LibName72=A:/kicad/Kicad Offical Libraries/kicad-library/library/microchip_pic12mcu
LibName73=A:/kicad/Kicad Offical Libraries/kicad-library/library/microchip_pic16mcu
LibName74=A:/kicad/Kicad Offical Libraries/kicad-library/library/microchip_pic18mcu
LibName75=A:/kicad/Kicad Offical Libraries/kicad-library/library/microchip_pic32mcu
LibName76=A:/kicad/Kicad Offical Libraries/kicad-library/library/microcontrollers
LibName77=A:/kicad/Kicad Offical Libraries/kicad-library/library/motor_drivers
LibName78=A:/kicad/Kicad Offical Libraries/kicad-library/library/motorola
LibName79=A:/kicad/Kicad Offical Libraries/kicad-library/library/motors
LibName80=A:/kicad/Kicad Offical Libraries/kicad-library/library/msp430
LibName81=A:/kicad/Kicad Offical Libraries/kicad-library/library/nordicsemi
LibName82=A:/kicad/Kicad Offical Libraries/kicad-library/library/nxp_armmcu
LibName83=A:/kicad/Kicad Offical Libraries/kicad-library/library/onsemi
LibName84=A:/kicad/Kicad Offical Libraries/kicad-library/library/opto
LibName85=A:/kicad/Kicad Offical Libraries/kicad-library/library/Oscillators
LibName86=A:/kicad/Kicad Offical Libraries/kicad-library/library/philips
LibName87=A:/kicad/Kicad Offical Libraries/kicad-library/library/power
LibName88=A:/kicad/Kicad Offical Libraries/kicad-library/library/Power_Management
LibName89=A:/kicad/Kicad Offical Libraries/kicad-library/library/powerint
LibName90=A:/kicad/Kicad Offical Libraries/kicad-library/library/pspice
LibName91=A:/kicad/Kicad Offical Libraries/kicad-library/library/references
LibName92=A:/kicad/Kicad Offical Libraries/kicad-library/library/regul
LibName93=A:/kicad/Kicad Offical Libraries/kicad-library/library/relays
LibName94=A:/kicad/Kicad Offical Libraries/kicad-library/library/rfcom
LibName95=A:/kicad/Kicad Offical Libraries/kicad-library/library/sensors
LibName96=A:/kicad/Kicad Offical Libraries/kicad-library/library/silabs
LibName97=A:/kicad/Kicad Offical Libraries/kicad-library/library/siliconi
LibName98=A:/kicad/Kicad Offical Libraries/kicad-library/library/stm8
LibName99=A:/kicad/Kicad Offical Libraries/kicad-library/library/supertex
LibName100=A:/kicad/Kicad Offical Libraries/kicad-library/library/switches
LibName101=A:/kicad/Kicad Offical Libraries/kicad-library/library/texas
LibName102=A:/kicad/Kicad Offical Libraries/kicad-library/library/transf
LibName103=A:/kicad/Kicad Offical Libraries/kicad-library/library/transistors
LibName104=A:/kicad/Kicad Offical Libraries/kicad-library/library/ttl_ieee
LibName105=A:/kicad/Kicad Offical Libraries/kicad-library/library/valves
LibName106=A:/kicad/Kicad Offical Libraries/kicad-library/library/video
LibName107=A:/kicad/Kicad Offical Libraries/kicad-library/library/wiznet
LibName108=A:/kicad/Kicad Offical Libraries/kicad-library/library/Worldsemi
LibName109=A:/kicad/Kicad Offical Libraries/kicad-library/library/Xicor
LibName110=A:/kicad/Kicad Offical Libraries/kicad-library/library/xilinx
LibName111=A:/kicad/Kicad Offical Libraries/kicad-library/library/Zilog
LibName112=A:/kicad/automotive-light-controller/automotive-light-controller-cache
LibName113=lp2950
LibName114=G3MB-SSR
LibName115=JACK_STEREO
