update=13/11/2016 1:42:54 PM
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=../../kicad/Libraries
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=microcontrollers
LibName13=dsp
LibName14=microchip
LibName15=analog_switches
LibName16=motorola
LibName17=texas
LibName18=intel
LibName19=audio
LibName20=interface
LibName21=digital-audio
LibName22=philips
LibName23=display
LibName24=cypress
LibName25=siliconi
LibName26=opto
LibName27=atmel
LibName28=contrib
LibName29=valves
LibName30=A:/kicad/Kicad Offical Libraries/kicad-library/library/74xgxx
LibName31=A:/kicad/Kicad Offical Libraries/kicad-library/library/74xx
LibName32=A:/kicad/Kicad Offical Libraries/kicad-library/library/ac-dc
LibName33=A:/kicad/Kicad Offical Libraries/kicad-library/library/actel
LibName34=A:/kicad/Kicad Offical Libraries/kicad-library/library/adc-dac
LibName35=A:/kicad/Kicad Offical Libraries/kicad-library/library/Altera
LibName36=A:/kicad/Kicad Offical Libraries/kicad-library/library/analog_devices
LibName37=A:/kicad/Kicad Offical Libraries/kicad-library/library/analog_switches
LibName38=A:/kicad/Kicad Offical Libraries/kicad-library/library/atmel
LibName39=A:/kicad/Kicad Offical Libraries/kicad-library/library/audio
LibName40=A:/kicad/Kicad Offical Libraries/kicad-library/library/battery_management
LibName41=A:/kicad/Kicad Offical Libraries/kicad-library/library/bbd
LibName42=A:/kicad/Kicad Offical Libraries/kicad-library/library/brooktre
LibName43=A:/kicad/Kicad Offical Libraries/kicad-library/library/cmos_ieee
LibName44=A:/kicad/Kicad Offical Libraries/kicad-library/library/cmos4000
LibName45=A:/kicad/Kicad Offical Libraries/kicad-library/library/conn
LibName46=A:/kicad/Kicad Offical Libraries/kicad-library/library/contrib
LibName47=A:/kicad/Kicad Offical Libraries/kicad-library/library/cypress
LibName48=A:/kicad/Kicad Offical Libraries/kicad-library/library/dc-dc
LibName49=A:/kicad/Kicad Offical Libraries/kicad-library/library/device
LibName50=A:/kicad/Kicad Offical Libraries/kicad-library/library/digital-audio
LibName51=A:/kicad/Kicad Offical Libraries/kicad-library/library/diode
LibName52=A:/kicad/Kicad Offical Libraries/kicad-library/library/display
LibName53=A:/kicad/Kicad Offical Libraries/kicad-library/library/dsp
LibName54=A:/kicad/Kicad Offical Libraries/kicad-library/library/elec-unifil
LibName55=A:/kicad/Kicad Offical Libraries/kicad-library/library/ESD_Protection
LibName56=A:/kicad/Kicad Offical Libraries/kicad-library/library/ftdi
LibName57=A:/kicad/Kicad Offical Libraries/kicad-library/library/gennum
LibName58=A:/kicad/Kicad Offical Libraries/kicad-library/library/graphic
LibName59=A:/kicad/Kicad Offical Libraries/kicad-library/library/hc11
LibName60=A:/kicad/Kicad Offical Libraries/kicad-library/library/intel
LibName61=A:/kicad/Kicad Offical Libraries/kicad-library/library/interface
LibName62=A:/kicad/Kicad Offical Libraries/kicad-library/library/ir
LibName63=A:/kicad/Kicad Offical Libraries/kicad-library/library/Lattice
LibName64=A:/kicad/Kicad Offical Libraries/kicad-library/library/linear
LibName65=A:/kicad/Kicad Offical Libraries/kicad-library/library/logo
LibName66=A:/kicad/Kicad Offical Libraries/kicad-library/library/maxim
LibName67=A:/kicad/Kicad Offical Libraries/kicad-library/library/memory
LibName68=A:/kicad/Kicad Offical Libraries/kicad-library/library/microchip
LibName69=A:/kicad/Kicad Offical Libraries/kicad-library/library/microchip_dspic33dsc
LibName70=A:/kicad/Kicad Offical Libraries/kicad-library/library/microchip_pic10mcu
LibName71=A:/kicad/Kicad Offical Libraries/kicad-library/library/microchip_pic12mcu
LibName72=A:/kicad/Kicad Offical Libraries/kicad-library/library/microchip_pic16mcu
LibName73=A:/kicad/Kicad Offical Libraries/kicad-library/library/microchip_pic18mcu
LibName74=A:/kicad/Kicad Offical Libraries/kicad-library/library/microchip_pic32mcu
LibName75=A:/kicad/Kicad Offical Libraries/kicad-library/library/microcontrollers
LibName76=A:/kicad/Kicad Offical Libraries/kicad-library/library/motor_drivers
LibName77=A:/kicad/Kicad Offical Libraries/kicad-library/library/motorola
LibName78=A:/kicad/Kicad Offical Libraries/kicad-library/library/motors
LibName79=A:/kicad/Kicad Offical Libraries/kicad-library/library/msp430
LibName80=A:/kicad/Kicad Offical Libraries/kicad-library/library/nordicsemi
LibName81=A:/kicad/Kicad Offical Libraries/kicad-library/library/nxp_armmcu
LibName82=A:/kicad/Kicad Offical Libraries/kicad-library/library/onsemi
LibName83=A:/kicad/Kicad Offical Libraries/kicad-library/library/opto
LibName84=A:/kicad/Kicad Offical Libraries/kicad-library/library/Oscillators
LibName85=A:/kicad/Kicad Offical Libraries/kicad-library/library/philips
LibName86=A:/kicad/Kicad Offical Libraries/kicad-library/library/power
LibName87=A:/kicad/Kicad Offical Libraries/kicad-library/library/Power_Management
LibName88=A:/kicad/Kicad Offical Libraries/kicad-library/library/powerint
LibName89=A:/kicad/Kicad Offical Libraries/kicad-library/library/pspice
LibName90=A:/kicad/Kicad Offical Libraries/kicad-library/library/references
LibName91=A:/kicad/Kicad Offical Libraries/kicad-library/library/regul
LibName92=A:/kicad/Kicad Offical Libraries/kicad-library/library/relays
LibName93=A:/kicad/Kicad Offical Libraries/kicad-library/library/rfcom
LibName94=A:/kicad/Kicad Offical Libraries/kicad-library/library/sensors
LibName95=A:/kicad/Kicad Offical Libraries/kicad-library/library/silabs
LibName96=A:/kicad/Kicad Offical Libraries/kicad-library/library/siliconi
LibName97=A:/kicad/Kicad Offical Libraries/kicad-library/library/stm8
LibName98=A:/kicad/Kicad Offical Libraries/kicad-library/library/supertex
LibName99=A:/kicad/Kicad Offical Libraries/kicad-library/library/switches
LibName100=A:/kicad/Kicad Offical Libraries/kicad-library/library/texas
LibName101=A:/kicad/Kicad Offical Libraries/kicad-library/library/transf
LibName102=A:/kicad/Kicad Offical Libraries/kicad-library/library/transistors
LibName103=A:/kicad/Kicad Offical Libraries/kicad-library/library/ttl_ieee
LibName104=A:/kicad/Kicad Offical Libraries/kicad-library/library/valves
LibName105=A:/kicad/Kicad Offical Libraries/kicad-library/library/video
LibName106=A:/kicad/Kicad Offical Libraries/kicad-library/library/wiznet
LibName107=A:/kicad/Kicad Offical Libraries/kicad-library/library/Worldsemi
LibName108=A:/kicad/Kicad Offical Libraries/kicad-library/library/Xicor
LibName109=A:/kicad/Kicad Offical Libraries/kicad-library/library/xilinx
LibName110=A:/kicad/Kicad Offical Libraries/kicad-library/library/Zilog
LibName111=A:/kicad/automotive-light-controller/automotive-light-controller-cache
LibName112=lp2950
LibName113=G3MB-SSR
